### ISSUE TITLE
Difference between the ckpts?

### ISSUE THREAD

**Issue by RichardSunnyMeng** [OPTML-Group/UnlearnCanvas#6]
Hi, authors. I want to use the style classifier but don't know the differences between style50_cls.pth and style50.pth. What is the difference between them? And I find that there are 51 style classes in the codes but the file names indicate that there are 50 classes?

**Comment by NormalUhr** [comment]
Hi, thanks for your interest in our work. The style50_cls.pth is the checkpoint for vit to do object-wise classification, so it has a classification head with only 20 classes. The style50.pth aims to do style classification. Its classification head has 51 classes because there are 50 artistic styles + 1 photo style (no artistic style). Hope this answers your questions.

**Comment by RichardSunnyMeng** [comment]
Thanks for your careful comment!

**Comment by YuanXun2024** [comment]
Hi,

Here you said there were only "50 artistic styles + 1 photo style". But in the Google Drive you provided, there are 61 styles. Which ones did you not use for the UnlearnCanvas paper?

Thank you!
